### ISSUE TITLE
Export function generates many Notices

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/l10n_server#1]
I tested the export function: http://localizetest.tenutoweb.com/translate/languages/hu/export
Options:
![kép](https://user-images.githubusercontent.com/8567234/230798314-81f5e12d-2028-4251-a6e8-688bb17e6229.png)

I exported the file successfully. But when I refresh the page, there were many notices:
"Notice: Undefined property: stdClass::$is_suggestion in l10n_community_export() (line 467 of /home/tenutowe/localize_test/modules/l10n_server/l10n_community/export.inc)."

![kép](https://user-images.githubusercontent.com/8567234/230798333-5dfb2886-0763-481a-9f9b-89a477c75856.png)

**Comment by argiepiano** [comment]
Thanks for reporting @VasasA! The same bug exists in the D7 version, but it hasn't been reported there. These Notices are avoided if you click "Add Hungarian translations".

I believe the fix is pretty straightforward. However, if what you are trying to do is download the `.po` file, the best way to do that is to do it through `translate/downloads` rather than export.
