### ISSUE TITLE
Provide exact match search option at the translate filter that applies to the contains input field

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/l10n_server#29]
See https://github.com/backdrop-ops/localize.backdropcms.org/issues/50

**Comment by lourdas** [comment]
I tested the changes by the PR locally and they seem to work. Reviews are welcome!

**Comment by argiepiano** [comment]
@lourdas thanks so much for providing the PR. It works great, but I'm experiencing some css issues with the new field:

<img width="1182" alt="Screen Shot 2024-03-25 at 9 37 03 PM" src="https://github.com/backdrop-contrib/l10n_server/assets/9938978/a7f2030d-bd2c-4555-b3e0-8a281a6aef30">

The problem seems to be the height value for

```css
.l10n-server-filter .filter-widget {
    float: left;
    padding: 0 1em 0 0;
    height: 6em;
}
```

With the Basis theme (which is what I'm using for the screenshot above), this works better with a height of 8em. The result is more separation, so that the label for Limit is not superimposed with the "suggestions" select box. Have you checked this with he Borg Localize theme? Is there a problem there as well? 

Can you please try changing that height value and see if that creates issues with Borg?

**Comment by lourdas** [comment]
I'm attaching two screenshots for the production localize server, the first is from Vivaldi (Chromium based), the second is from Firefox.
![Screenshot_20240326_124113](https://github.com/backdrop-contrib/l10n_server/assets/397916/a5a08a20-e774-42c8-9bae-7314c9811bbd)
![Screenshot_20240326_124145](https://github.com/backdrop-contrib/l10n_server/assets/397916/3e9defb9-e018-4648-b82e-3c200319b043)

So, even as it stands now, the existing site already has some CSS issues. Maybe these should be first fixed instead of focusing on the current PR? And to be honest, I'm not the best guy with CSS. I will try locally and see if I manage to fix any issues.

**Comment by argiepiano** [comment]
Thanks. Given that this problem existed before, then, I'll open a separate issue. So your PR is good to go. I'll merge now.
