### ISSUE TITLE
Format the groups on the "Localization server jump form" to be an item list.

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/l10n_server#30]
When looking at the home page of https://localize.backdropcms.org/translate/projects/backdropcms I think the list of groups would look nicer as an item list, than as a comma separated list. If we want, we can style the item list to look like a comma-separated list, but we cannot do the reverse.

**Comment by olafgrabienski** [comment]
For the record, is this about the "Your groups" list under the "Quick navigation" heading, or about the "Pick a language" list?

**Comment by argiepiano** [comment]
Thanks, @jenlampton! Works well.

@olafgrabienski, this is the list under Quick Navigation:
<img width="417" alt="Screen Shot 2024-03-25 at 10 06 12 PM" src="https://github.com/backdrop-contrib/l10n_server/assets/9938978/f20f25a3-ba98-4781-b41a-2b1824578253">

It looks like this was already changed in the localize site. Also the "Pick a language" has been transformed into a select list. @jenlampton, would you like to create a new issue for that "Pick a language" widget, to make it into select, instead of radios?

EDIT: Actually the current code switches to select if there are more than 5 options.
